# Generated by Django 3.0.8 on 2020-07-08 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('be_app', '0002_auto_20200708_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.TextField(max_length=50, null=True),
        ),
    ]
