# Generated by Django 3.0.8 on 2020-07-09 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('be_app', '0006_auto_20200709_2158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='nationality',
        ),
        migrations.AddField(
            model_name='profile',
            name='first_name',
            field=models.CharField(default=0, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='last_name',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
