# Generated by Django 3.0.8 on 2020-07-14 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('be_app', '0008_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
    ]
