# Generated by Django 3.0.8 on 2020-07-19 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('be_app', '0009_auto_20200714_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
