# Generated by Django 3.0.8 on 2020-07-19 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('be_app', '0010_profile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
    ]
